git in prompt

diff --git a/07_prompt b/07_prompt
--- a/07_prompt
+++ b/07_prompt
@@ -1,3 +1,21 @@
+function git-need-to-push() {
+  if pushtime=$(echo $1 | grep 'Your branch is ahead' 2> /dev/null); then
+    echo ">"
+  fi
+}
+function git-prompt() {
+  gstatus=$(git status 2> /dev/null)
+  branch=$(echo $gstatus | head -1 | sed 's/^# On branch //')
+  dirty=$(echo $gstatus | sed 's/^#.*$//' | tail -2 | grep 'nothing to commit (working directory clean)'; echo $?)
+  if [[ x$branch != x ]]; then
+    dirty_color=$fg[green]
+    push_status=$(git-need-to-push $gstatus 2> /dev/null)
+    if [[ $dirty = 1 ]] { dirty_color=$fg[red] }
+      [ x$branch != x ] && echo " %{$dirty_color%}$branch%{$reset_color%} $push_status"
+    fi
+}
+
+
 # Global colors
 for COLOR in CYAN MAGENTA BLUE RED GREEN YELLOW WHITE BLACK; do
     eval PR_BRIGHT_$COLOR='%{$fg[${(L)COLOR}]%}'
@@ -16,20 +34,21 @@ function zle-line-init zle-keymap-select {
 zle -N zle-line-init
 zle -N zle-keymap-select
 
-## A custom prompt that looks like this:
+# ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~
+# A custom prompt:
 #
-# !4386  +0  *noah  @downbe  .20100313 16:24:44 CST  ^0
+# !4386  +0  *noah  @downbe  .20100313 16:24:44 CST  ?0
 # %/# 
 #
-# The value prefixes are quasi-mnemonic.  E.g.,
+# The value prefixes are semi-mnemonic.  E.g.,
 #   !n runs the command with history number n
 #   + is displayed in output of jobs command e.g., 
 #       $ jobs
 #       [1]  + suspended  vim
-#   * of course, the user is represented by a star
-#   @ hostname 
+#   * of course, the logged-in user is represented by a star
+#   @ at hostname 
 #   . dot for where we are right now (in terms of time)
-#   ^ for last job
+#   $? for exit status of last job (as in $?)
 #
 # history num
 # num jobs
@@ -44,9 +63,11 @@ PROMPT='\
 *${PR_BOLD_GREEN}%n${PR_RESET}$SEP\
 @${PR_BOLD_MAGENTA}%m${PR_RESET}$SEP\
 .${PR_BOLD_BLUE}%D{%Y%m%d %T %Z}${PR_RESET}$SEP\
-^${PR_BOLD_RED}%?${PR_RESET}$SEP\
+?${PR_BOLD_RED}%?${PR_RESET}$SEP\
 ${VI_MODE}${PR_RESET}
 %/
 %# '
+
+RPROMPT='`git-prompt`'
 
 # vim: ft=zsh
